# Generated by Django 5.2.6 on 2025-10-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
