# Generated by Django 5.2.6 on 2025-11-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score for category prediction (0.0-1.0)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_manually_categorized",
            field=models.BooleanField(
                default=False, help_text="True if category was manually set by user"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="predicted_category",
            field=models.CharField(
                blank=True,
                help_text="Original predicted category before manual correction",
                max_length=64,
            ),
        ),
    ]
