# Generated by Django 5.2.6 on 2025-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_transaction_category_confidence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excluded_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of category names to exclude from dashboard calculations and displays",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dashboard Settings",
            },
        ),
    ]
