import os

import pandas as pd

"""Finance utility functions for transaction categorization and processing."""

CATEGORY_KEYWORDS = {
    "Groceries": [
        "coop",
        "migros",
        "aldi",
        "lidl",
        "denner",
        "supermarket",
        "grocery",
        "carrefour",
        "migrolino",
        "coop to go",
        "volg",
        "edeka",
        "franprix",
    ],
    "Transport": [
        "sbb",
        "vbz",
        "bus",
        "train",
        "tram",
        "uber",
        "taxi",
        "easyr",
        "easyrider",
        "ratp",
    ],
    "Insurance": ["sanitas", "axa", "versicherung", "insurance"],
    "Dining": [
        "restaurant",
        "cafe",
        "bar",
        "mc donald",
        "starbucks",
        "pizza",
        "kebab",
        "dining",
        "resto",
        "steakhouse",
        "le crobag",
        "burger king",
        "selecta",
        "orient world",
        "paul",
        "relay",
        "toogoodtogo",
        "too good to go",
        "vending machine",
        "sv group",
        "Gletscherrest.",
        "asiaway",
        "buchmann",
        "gelati",
        "nooba",
        "rice up",
        "nordbrücke",
        "amboss rampe",
        "les halles",
        "tiny fish",
        "monocle",
        "glace",
        "gelateria",
    ],
    "Salary": ["salary", "eraneos", "payroll", "lohn"],
    "Shopping": [
        "galaxus",
        "digitec",
        "decathlon",
        "shopping",
        "store",
        "shop",
        "boutique",
        "hm",
        "jumbo",
        "blattner",
        "fnac",
        "brocki-land",
        "aliexpress",
        "amazon",
    ],
    "Utilities": [
        "swisscom",
        "sunrise",
        "telecom",
        "internet",
        "electricity",
        "wasser",
        "water",
        "gas",
        "utility",
        "apple",
        "swiss post",
        "www.1global.com",
        "salt mobile",
    ],
    "Car": ["garage", "parking", "park", "parkingpay"],
    "Health": [
        "pharmacy",
        "apotheke",
        "doctor",
        "arzt",
        "hospital",
        "clinic",
        "dm",
        "dr",
        "Centre Ophtalmol",
        "coiffure",
    ],
    "Travel": [
        "hotel",
        "hostel",
        "airbnb",
        "booking.com",
        "flight",
        "airline",
        "bahn",
        "train",
        "bookaway",
        "rentcars",
        "easyjet",
        "autostrade",
        "titls rotair",
        "bahn",
        "sncf",
        "bp",
        "shell",
        "socar",
        "iberia",
        "benzin discount",
        "alpes recepcion",
        "edelweiss",
        "esso",
    ],
    "Bank Transfer": [
        "transfer",
        "account transfer",
        "sepa",
        "wire",
        "überweisung",
        "revolut france, succursale de revolut bank uab",
        "pierre helmut eichmeyer",
        "eichmeyer",
    ],
    "Investment": ["degen", "crypto", "coinbase", "binance", "investment", "etoro"],
    "Leisure": [
        "cinema",
        "theater",
        "concert",
        "event",
        "leisure",
        "museo",
        "museum",
        "steam",
        "gotcourts",
        "kunsthaus",
        "disney+",
        "yoga",
        "ground news",
        "kobo",
        "audible",
        "netflix",
        "spotify",
        "hallenbad",
        "ticketcorner",
    ],
    "Fee": ["fee", "charge", "gebühr"],
    "Vault": [
        "pocket withdrawal",  # More specific, must come before "withdrawal"
        "to pocket",
        "from pocket",
        "pocket",
        "vault",
        "to chf tablet",
        "to chf gaming rig",
        "to eur",
        "to chf",
    ],
    "Cash Withdrawal": [
        "atm",
        "cash withdrawal",
        "geldautomat",
        "bankomat",
        "cajero",
        "bancomat",
        "withdrawal",
    ],
    "Work": ["isc2"],
    "Uncounted": [
        "balance migration",
        "exchanged to",
        "payment from",
        "top-up",
        "topup",
        "payment from david georges j colonna",
    ],
    "Refund": ["refund", "refunded", "reimbursement"],
    "Rent": [
        # Note: KAJETAN rent payments are handled by special rule in preprocess_statement.py
        # (specific amounts: 1585.5, 1575.5)
        "rent",
        "miete",
        "immobilien",
        "bruppacher verwaltungs ag",
        "bruppacher",
        "mariusz tomasz jedrzejewski",
        "jedrzejewski",
    ],
    "Donation": ["pro infirmis"],
    "Other": [],
}
