import os

import pandas as pd

"""Finance utility functions for transaction categorization and processing."""

CATEGORY_KEYWORDS = {
    "Groceries": [
        "coop",
        "migros",
        "aldi",
        "lidl",
        "denner",
        "supermarket",
        "grocery",
        "carrefour",
        "migrolino",
        "coop to go",
        "volg",
        "edeka",
        "franprix",
    ],
    "Transport": [
        "sbb",
        "vbz",
        "bus",
        "train",
        "tram",
        "uber",
        "taxi",
        "easyr",
        "easyrider",
        "ratp",
    ],
    "Insurance": ["sanitas", "axa", "versicherung", "insurance"],
    "Dining": [
        "restaurant",
        "cafe",
        "bar",
        "mc donald",
        "starbucks",
        "pizza",
        "kebab",
        "dining",
        "resto",
        "steakhouse",
        "le crobag",
        "burger king",
        "selecta",
        "orient world",
        "paul",
        "relay",
        "toogoodtogo",
        "too good to go",
        "vending machine",
        "sv group",
        "Gletscherrest.",
        "asiaway",
        "buchmann",
        "gelati",
        "nooba",
        "rice up",
        "nordbrücke",
        "amboss rampe",
        "les halles",
        "tiny fish",
        "monocle",
        "glace",
        "gelateria",
    ],
    "Salary": ["salary", "eraneos", "payroll", "lohn"],
    "Shopping": [
        "galaxus",
        "digitec",
        "decathlon",
        "shopping",
        "store",
        "shop",
        "boutique",
        "hm",
        "jumbo",
        "blattner",
        "fnac",
        "brocki-land",
        "aliexpress",
        "amazon",
    ],
    "Utilities": [
        "swisscom",
        "sunrise",
        "telecom",
        "internet",
        "electricity",
        "wasser",
        "water",
        "gas",
        "utility",
        "apple",
        "swiss post",
        "www.1global.com",
    ],
    "Car": ["garage", "parking", "park", "parkingpay"],
    "Health": [
        "pharmacy",
        "apotheke",
        "doctor",
        "arzt",
        "hospital",
        "clinic",
        "dm",
        "dr",
        "Centre Ophtalmol",
        "coiffure",
    ],
    "Travel": [
        "hotel",
        "hostel",
        "airbnb",
        "booking.com",
        "flight",
        "airline",
        "bahn",
        "train",
        "bookaway",
        "rentcars",
        "easyjet",
        "autostrade",
        "titls rotair",
        "bahn",
        "sncf",
        "bp",
        "shell",
        "socar",
        "iberia",
        "benzin discount",
        "alpes recepcion",
        "edelweiss",
        "esso",
    ],
    "Bank Transfer": [
        "transfer",
        "account transfer",
        "sepa",
        "wire",
        "überweisung",
        "revolut france, succursale de revolut bank uab",
        "payment from",
        "top-up",
    ],
    "Investment": ["degen", "crypto", "coinbase", "binance", "investment", "etoro"],
    "Leisure": [
        "cinema",
        "theater",
        "concert",
        "event",
        "leisure",
        "museo",
        "museum",
        "steam",
        "gotcourts",
        "kunsthaus",
        "disney+",
        "yoga",
        "ground news",
        "kobo",
        "audible",
        "netflix",
        "spotify",
        "hallenbad",
    ],
    "Standing Order": ["standing order"],
    "Fee": ["fee", "charge", "gebühr"],
    "Cash Withdrawal": [
        "atm",
        "cash withdrawal",
        "geldautomat",
        "bankomat",
        "cajero",
        "bancomat",
    ],
    "Work": ["isc2"],
    "Uncounted": ["balance migration", "exchanged to"],
    "Vault": ["pocket", "vault", "pocket withdrawal"],
    "Refund": ["refund"],
    "Rent": ["rent", "miete", "immobilien"],
    "Donation": ["pro infirmis"],
    "Other": [],
}
